services:
  - type: web
    name: blurry-guess-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.cjs"
    envVars:
      - key: PORT
        value: 3001
